name: Build and Push Docker Images

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and push menu-service image
      uses: docker/build-push-action@v4
      with:
        context: ./menu-services
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/menu-service:latest

    - name: Build and push order-service image
      uses: docker/build-push-action@v4
      with:
        context: ./order-services
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/order-service:latest

    - name: Build and push inventory-service image
      uses: docker/build-push-action@v4
      with:
        context: ./inventory-services
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/inventory-service:latest

    - name: Build and push customer-service image
      uses: docker/build-push-action@v4
      with:
        context: ./customer-services
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/customer-service:latest

    - name: Build and push payment-service image
      uses: docker/build-push-action@v4
      with:
        context: ./payment-services
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/payment-service:latest

    - name: Build and push loyalty-service image
      uses: docker/build-push-action@v4
      with:

        context: ./loyalty-services
        push: true
       tags: ${{ secrets.DOCKER_USERNAME }}/loyalty-service:latest
